version: 2.1
orbs:
  node: circleci/node@1.1.4
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '10.16.3'
      - node/with-cache:
          cache-key: package-lock.json
          steps:
            - run: npm ci
      - run: npm run lint
      - run: ./node_modules/.bin/danger ci
