title: Graphics Context Settings
description: Defines the opacity and blend mode of a style or shadow
type: object
properties:
  _class: { const: graphicsContextSettings }
  blendMode: { $ref: ../enums/blend-mode.schema.yaml }
  opacity: { type: number }
