[build]
	base    = ""
	publish = "docs-website/_site"
	command = "cd docs-website && bundle install && jekyll build"
# This makes sure that we don't build the site for changes outside the docs or docs-website folders
	ignore = "git diff --quiet HEAD^..HEAD -- docs docs-website"
