# Site settings
title: Sketch Developers
email: mail@sketch.com
url: https://developer.sketch.com
github_repo: https://github.com/sketch-hq/SketchAPI
show_dir_listing: false

# Build settings
incremental: true
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

plugins:
  - jekyll-redirect-from

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

sass:
  style: compressed

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - .sass-cache
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - DEVNOTES.md

# Dynamic Content
collections:
  actions:
    output: true
    permalink: /reference/action/:path/
  posts:
    output: true
    permalink: /blog/:path/
  api-references: # this comes from the SketchAPI repo
    output: false

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single-page"
  -
    scope:
      type: "actions"
    values:
      layout: "action"
      search: true
  -
    scope:
      type: "pages"
    values:
      layout: "sidebar-page"
      search: true
  -
    scope:
      type: "posts"
    values:
      layout: "post"
